### ISSUE TITLE
git repo needs to be amended https://git.sickrage.ca/SiCKRAGE/

### ISSUE THREAD

**Issue by wattsra** [linuxserver/docker-sickrage-armhf#12]
Please can you update the docker image so that it points to the new SickRage repository hosted on a private gitlab instance. The current git hub repo no longer exists

https://git.sickrage.ca/SiCKRAGE/sickrage

**Comment by fguiet** [comment]
+1

Check for update is not working and one can see the following stuff in logs:

2018-12-22 11:59:01 MAIN :: Updating network timezones failed, this can happen from time to time. URL: http://sick-rage.github.io/sb_network_timezones/network_timezones.txt

**Comment by thelamer** [comment]
This has actually shifted to the sickchill and this repo is now depreciated as the main one is now multi arch. Closing this issue.
